// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/BauhausRestaurantIndex-f1_FIn/App.tsx": () => import("../components/mockups/templates/BauhausRestaurantIndex-f1_FIn/App.tsx"),
  "./components/mockups/templates/FirstClassBoardingPass-Z-9I6L/BoardingPass.tsx": () => import("../components/mockups/templates/FirstClassBoardingPass-Z-9I6L/BoardingPass.tsx"),
  "./components/mockups/templates/OnCallContactGrid-jyha1Z/App.tsx": () => import("../components/mockups/templates/OnCallContactGrid-jyha1Z/App.tsx"),
  "./components/mockups/templates/MidCenturyChocolatePoster-gTKMBo/App.tsx": () => import("../components/mockups/templates/MidCenturyChocolatePoster-gTKMBo/App.tsx"),
  "./components/mockups/templates/VintageFashionFundingNotification-xhtfRi/App.tsx": () => import("../components/mockups/templates/VintageFashionFundingNotification-xhtfRi/App.tsx")
};
